# Generated by Django 5.2.4 on 2025-08-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_size_userimage'),
    ]

    operations = [
    # migrations.RemoveField(
    #     model_name='product',
    #     name='color',
    # ),
    # ... keep the other operations
    migrations.AlterField(
        model_name='cart',
        name='size',
        field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10, null=True),
    ),
    migrations.AlterField(
        model_name='orderitem',
        name='size',
        field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10, null=True),
    ),
    migrations.AlterField(
        model_name='product',
        name='size',
        field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10, null=True),
    ),
    migrations.CreateModel(
        name='ProductImage',
        fields=[
            # ... keep the ProductImage fields
        ],
    ),
]