# Generated by Django 5.2.4 on 2025-08-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_color_alter_cart_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
