# Generated by Django 5.2.4 on 2025-08-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cart_size_alter_orderitem_size_and_more'),
    ]

    operations = [
    ]
