# Generated by Django 5.2.4 on 2025-08-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_color'),
        ('core', '0013_fix_duplicate_columns'),
    ]

    operations = [
    ]
